{% if ansible_machine == "x86_64" -%}
  FROM debian:jessie
{% elif ansible_machine == "armv7l" -%}
  FROM resin/rpi-raspbian:jessie-20160831
{% else -%}
  # No docker base available for architecture: {{ansible_machine}}
{% endif %}
RUN apt-get -y update

# Retrieve iAstroHub code base
RUN apt-get -y install git
RUN git clone --depth 1 https://github.com/aruangra/iAstroHub.git /iAstroHub

# Install and configure web server
RUN apt-get -y install \
  nginx \
  php5-cgi \
  php5-cli \
  php5-common \
  php5-fpm
RUN sed -i "s/short_open_tag = Off/short_open_tag = On/g" /etc/php5/cgi/php.ini
RUN sed -i "s/short_open_tag = Off/short_open_tag = On/g" /etc/php5/cli/php.ini
RUN sed -i "s/short_open_tag = Off/short_open_tag = On/g" /etc/php5/fpm/php.ini
RUN mkdir -p /files
COPY files/* /files
RUN patch --follow-symlinks -l -i /files/nginx-default-site.patch /etc/nginx/sites-enabled/default
RUN service php5-fpm restart
RUN service nginx restart

