{% if ansible_machine == "x86_64" -%}
  FROM debian:jessie
{% elif ansible_machine == "armv7l" -%}
  FROM resin/rpi-raspbian:jessie-20160831
{% else -%}
  # No docker base available for architecture: {{ansible_machine}}
{% endif %}
RUN apt-get -y update

RUN apt-get -y install \
  git \
  net-tools \
  python \
  wget

RUN wget https://github.com/novnc/noVNC/archive/v{{version}}.tar.gz
RUN gunzip v{{version}}.tar.gz
RUN tar xf v{{version}}.tar

EXPOSE 6080

CMD ["/noVNC-0.6.1/utils/launch.sh", "--listen", "6080"]
